name: m
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.s
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.1.2
  google_fonts: ^1.1.2
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^9.2.0
  cached_network_image: ^2.0.0
  shimmer: ^2.0.0
  flutter_range_slider: ^1.4.0
  flutter_screenutil: ^5.3.1
  auto_size_text: ^3.0.0
  rive: ^0.7.12
  splashscreen: ^1.2.0
  after_layout: ^1.0.7+2
  flutter_svg: ^0.19.3







  flutter_localizations:
    sdk: flutter









dev_dependencies: 
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: "^0.0.1"


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo.png"

flutter_launcher_name:
  name: "Touri"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/flare/
    - assets/images/

  fonts:
    - family: SFUIText
      fonts:
        - asset: assets/fonts/sf/SFUIText-Regular.ttf
          weight: 500
        - asset: assets/fonts/sf/SFUIText-Semibold.ttf
          weight: 700
          
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/roboto/RobotoSlab-Bold.ttf
          weight: 900

        - asset: assets/fonts/roboto/RobotoSlab-Regular.ttf
          weight: 500


    - family: OpenSans
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Regular.ttf






  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
